from .base import *
# import rie, hyp
from . import rie, hyp

poisson_eq = Equation(
    'Poisson bracket of hydrodynamic type',
    Poisson(G, H),
    Poisson.rhs(G, H, mu, i, j, k),
)

A = Tensor('A', 2, 1)
evo_tensor = Definition(
    '$(1,1)$-tensors',
    A[mu,i,k] == g[mu,i,j] * h[j,k] + b[mu,i,j,k] * h[j]
)

hydro_evo = Definition(
    'evolution equation',
    Eq(
        u[i,t],
        L[i,j] * h[j] == Par(evo_tensor.rhs) * u[k,mu]
    )
)

jacobi_eq = Equation(
    'Jacobi identity',
    Cycler(Poisson(F, Poisson(G, H)), F, G, H),
    0,
)
V = Symbol('V')

Poi = Poisson(cdot, cdot)
poisson = Def(rf"""A bilinear bracket {Maps(
    Poi, Times(V, V), Reals
).bl} is called _Poisson_ if {Poi}

* is antisymmetric: {Poisson(F, G) == -Poisson(G, F)},
* is a derivation: {Poisson(F*G,H) == F*Poisson(G,H)+G*Poisson(F, H)} and
* satisfies the Jacobi-identity: {jacobi_eq}

JUST ADDED THIS TO BE ABLE TO REFERENCE IT, BUT THE BRACKET IS REALLY A BIVECTOR-field, I.E. IT MAY DEPEND ARBITRARILY ON U. WILL MOVE TO POISSON SECTION AND UPDATE.
""", 'Poisson bracket')
jacobi_eqs = ZeroEqs(
    # '',
    # 0,
    ASymm(g[mu,i,j], i,j),
    g[mu,i,j].d(u[k]) - 2*Symm(b[mu,i,j,k], i,j),
    Symm(ASymm(g[mu,i,l]*b[nu,j,k,l], i, j), mu, nu),
    Cycler(ASymm(g[mu,i,l]*b[nu,j,k,l], Tuple(i,mu), Tuple(j,nu)), i,j,k),
    Symm(Protect(
            g[mu,i,l]*ASymm(
                b[nu,j,k,l].d(u[m]),
                m,l
            ) +
            ASymm(
                b[mu,i,j,l]*b[nu, l, k, m],
                j, k
            )
        ),
        mu,nu
    ),
    ASymm(Protect(
        g[mu,i,l]*b[nu,j,k,m].d(u[l]) -
        # -b[nu,j,i,l]*b[mu,l,k,m] +
        # b[nu,j,k,l]*b[mu,i,l,m]),
        b[nu,i,j,l]*b[mu,l,k,m] -
        b[nu,i,k,l]*b[mu,j,l,m]),
        Tuple(i,mu), Tuple(j, nu)
    ),
    Symm(Protect(
        PDiff(
            g[mu,i,l]*ASymm(
                b[nu,j,k,l].d(u[m]),
                m,l
            ) +
            ASymm(
                b[mu,i,j,l]*b[nu, l, k, m],
                j, k
            ),
            u[n]
        ) - Cycler(
            b[mu, l, i, m] * ASymm(
                b[nu,j,k,l].d(u[m]),
                m,l
            ),
            i,j,k
        )),
        Tuple(mu, m), Tuple(nu, n)
    ),
)

hydro_1d_nd_theo = Theorem(rf"""Let {Det(g(u))!=0} and {d==1}. The bracket {hydro_brackets_u.ref} is a {poisson.long_ref} if and only if {g(u)} is an arbitrary flat {rie.prie.long_ref} metric and {b1[i,j,k](u)==-g1[i,l](u)*Gamma[j,l,k](u)}, where {Gamma[j,l,k](u)} is the Riemannian connection generated by the metric {g(u)}.""", "Stated without explicit proof in [Dubr1983b]. Can be proved by 'direct verification'.")

K = Symbol('K')
lam = Symbol('\lambda')
Gamma = Tensor(r'\Gamma', 2, 2)

comp_metric_def = Def(rf"""Two pseudo-Riemannian contravariant metrics {g[1,i,j](u)} and {g[2,i,j](u)} of constant Riemannian curvature {K[1]} and {K[2]}, respectively, are said to be _compatible_ if an arbitrary linear conbination {Eq(
    g1[i,j(u)],
    lam[1] * g[1,i,j](u) + lam[2] * g[2,i,j](u)
).bl} of these metrics, where {lam[1]} and {lam[2]} are arbitrary constants such that {Det(g1[i,j](u)) != 0}, is a metric of constant Riemannian curvature {lam[1]*K[1]+lam[2]*K[2]} and the coefficients of the corresponding Levi-Civita connections are related by the same linear formula {Eq(
    Gamma[i,j,k](u),
    lam[1]*Gamma[i,j,1,k](u) +
    lam[2]*Gamma[i,j,2,k](u)
).bl}.""")

hydro_nd_nd_comp_theo = Theorem(rf"""The metrics {g[mu,i,j]} defining a multidimensional Poisson bracket of the form {hydro_brackets_u.ref} are compatible.""", "See [Mokh1998], chapter II.")

T3 = T = Tensor('T', 3, 2)
T4 = Tensor('T', 4, 1)
T5 = Tensor('T', 5, 0)
Gamma = Tensor(r'\Gamma', 2, 2)
nabla = Tensor(r'\nabla', 1, 1)
T_eq = Eq(T[mu,nu,i,j,k], Gamma[nu,i,j,k]-Gamma[mu,i,j,k])

hydro_nd_nd_theo = Theorem(rf"""Flat non-degenerate metrics {g[mu, i, j](u)} and the Riemannian connections {Gamma[mu,i,j,k]} defined by these metrics (the Levi-Civita connections) generate a Poisson structure {hydro_brackets_u.ref} if and only if the tensors {T_eq} satisfy the following relations (no summation over {mu.l}): {Relations(
    ASymm(T5[mu,nu,i,j,k], i, k) == 0,
    Cycler(T[mu,nu,i,j,k],i,j,k) == 0,
    ASymm(T5[mu,nu,i,j,m]*T3[mu,nu,k,m,l], k, l)==0,
    nabla[mu, l]*T5[mu,nu,i,j,k]==0
).bl} where {Eq(
    T5[mu,nu,i,j,k],
    -g[nu,k,m]*T4[mu,nu,i,j,m],
    -g[nu,k,m]*g[mu,i,n]*T3[mu,nu,j,m,n]
)} and {nabla[mu,l]} is the covariant derivative associated with {g[mu]}.""")

hydro_ns_def = Def(rf"""A pair of metrics {g[1,i,j](u)} and {g[2,i,j](u)} is called _non-singular_ if the eigenvalues of this pair of metrics, i.e. the roots of the equation {Det(g[1,i,j](u)-lam*g[2,i,j](u))==0}, are distinct.""")

hydro_ns_const_theo = Theorem(rf"""If for a non-degenerate multidimensional Poisson bracket {hydro_brackets_u.ref} one of the metrics {g[mu,i,j](u)} forms non-singular pairs with all the remaining metrics of the bracket, then this Poisson bracket can be reduced to constant form by a local change of coordinates.""")

hydro_nd_canon_theo = Theorem(rf"""Consider a Poisson bracket  {hydro_brackets_u.ref}. If the metric {g[1,i,j]} is non-degenerate, then in flat coordinates $u$ where {g[1,i,j](u)} is constant and thus {b[1,i,j,k]==0}, every other metric {g[mu,i,j]} is _linear_.""", "See [Dubr1983a], theorem 1 and [Reyn2010], proposition 2.15.", "Non-degeneracy of _all_ metrics is not required.")

text = rf"""# Poisson brackets of hydrodynamic type
The main references are

* [Laur2013] Standard Poisson structures reference
* [Novi1982], [Dubr1983a], [Dubr1983b] (Slightly erroneous) initial papers
* [Gel'1980a], [Gel'1980b], [Gel'1982] preceeding papers
* [Grin1985] (Slightly erroneous) treatment of degenerate brackets of **constant rank**
* [Mokh1989] Correction of [Dubr1983a]
* [Mokh1992] Correction of [Grin1985]
* [Bogo2007a], [Bogo2007b] Extension of [Grin1985]
* [Savo2016b] Extension of [Grin1985]
* [Morr1980a] (Slightly erroneous) treatment of Maxwell-Vlasov
* [Morr1980b] Hamiltonian MHD
* [Wein1981] Correction of [Morr1980a]
* [Krog2001] Automatic Jacobi-check
* [Krog2010] Improvement of [Krog2001]
* [Kras2017] Inacessible, more general improvement of [Krog2010], [Krog2001]
* [Vito2019] Like [Kras2017]
* [Reyn2010] Hydrodynamic Poisson structures
* [Savo2016a] Hydrodynamic Poisson structures
* [Mokh1990], [Mokh1992] Nonlocal generalization
"""

hydrodynamic = Def(rf"""A {poisson.long_ref} {Poi} is called _hydrodynamic_ if it satisfies {hydro_brackets_u.bl}.""", 'hydrodynamic')
energy_density = Definition('energy density', h, Contains(h, Cinf(tspace)))
hydrodynamic_H = Def(rf"""A functional (or Hamiltonian) {Maps(H, uspace, Reals).bl} is called _hydrodynamic_ if it is of the form {hydro_functionals.bl} for some {energy_density.lm}.""", 'hydrodynamic')

# {hydro_brackets_u.m}

text += rf"""

{poisson}
In [Dubr1983a] and [Dubr1983b] Dubrovin and Novikov introduced Poisson brackets and Hamiltonians of _hydrodynamic type_:
{hydrodynamic}
{hydrodynamic_H}
By requiring that brackets and Hamiltonians do not depend themselves on spatial
derivatives of the unknown {fields.lm}, we ensure that the resulting evolution equation will be a {hyp.qpde_def.long_ref}.



For any two Functionals {F.m} and {H.m} we get
{hydro_brackets_h.bl}
with {L_op.im}. Finally, given a Poisson bracket and a hydrodynamic Hamiltonian functional $H$ we get the {hydro_evo.m}, where we can identify the {evo_tensor.m}.

For the above bracket to be Poisson, it has to satisfy the {jacobi_eq.m} for all hydrodynamic Functionals $F, G, H$ which, while innocent looking, translates to (see [Mokh1998], Lemma 2.1):
{jacobi_eqs.bl}"""

met_non_deg = Def(rf"""A metric {g(u)} is called _non-degenerate_ if {Det(g(u)) != 0} everywhere.""", 'non-degenerate')

poi_non_deg = Def(rf"""A Poisson bracket {hydro_brackets_u.ref} is called _non-degenerate_ if all metrics {g[mu](u)} are {met_non_deg.long_ref}.""", 'non-degenerate')

text += rf"""

## with nondegenerate metric
{met_non_deg}

{poi_non_deg}

### in one spatial dimension

The main result, due to Dubrovin and Novikov ([Dubr1983b], theorem 1) and most succinctly stated in [Mokh2000], is the following
{hydro_1d_nd_theo}

Due to flatness of the metric, we immediately get existence of (local) coordinates $u$ where {g[i,j](u) == e[i]*Dirac[i,j]} with {e[i] == PlusMinus(1)} and {b(u) == 0}. Hence _all_ non-degenerate one-dimensional Poisson brackets are classified by the signature of their metric.

### in multiple spatial dimensions
A generalization of {hydro_1d_nd_theo.lref}, summarized in [Mokh2006], uses heavily the notion of _compatible metrics_ developed in [Mokh2000]: {comp_metric_def}

This definition naturally mirrors the definition of _compatible Poisson brackets_, of which linear combinations are again required to be Poisson brackets (see e.g. [Fera2001] or [Mokh2002b]). Indeed, the following result is immediate: {hydro_nd_nd_comp_theo}

However, this is far from enough. Indeed, again from [Mokh1998], theorem 2.1: {hydro_nd_nd_theo}
Similarly to the case of one spatial dimension, there are multi-dimensional hydrodynamic Poisson brackets that can be reduced to _constant_ form. However, contrary to the one-dimensional case, non-degeneracy of the associated metric(s) is not a sufficient condition. Instead, we need additionally that the _obstruction tensors_ {T3[mu,nu,i,j,k]} are identically zero. We will need the concept of _non-singular_ pairs of metrics: {hydro_ns_def}

Finally we can state {hydro_ns_const_theo}

And for all other (non-degenerate) Poisson brackets we have {hydro_nd_canon_theo}

## with degenerate metric

### in one spatial dimension

Following the classification of non-degenerate one-dimensional Poisson brackets {hydro_brackets_u.ref} in [Dubr1983a], Grinberg provided answers to the question of classification of _degenerate_ one-dimensional Poisson brackets with metric {g(u)} of constant rank in [Grin1985]. However, proofs were lacking in the literature until the publication of [Bogo2007a]. We will summarize the main statements."""

L = Symbol('L')
T = Symbol('T')
star = Symbol('*')
# Ts = Symbol('T^*')
Ts = Sup(T, star)
v = Vector('v')
w = Covector('w')
O = Symbol(r'\mathcal{O}')
F = Symbol(r'\mathcal{F}')

tanspace = Definition(
    'tangent space',
    T[u](tspace)
)

cotanspace = Definition(
    'cotangent space',
    Ts[u](tspace)
)
Lu = Definition(
    'distribution',
    Subset(
        L[u] == MySet(
            Contains(v, tanspace),
            SuchThat(
                Exists(Contains(w, Ts[u])),
                v[i] == g[i,j](u)*w[j]
            )
        ),
        T[u](tspace)
    )
)
Ok = Definition(
    'subsets of rank $k$',
    Subset(
        O[k] == MySet(
            Contains(u, tspace),
            Rank(g(u)) == k
        ),
        tspace
    )
)
A1 = Tensor('A', 1, 1)
b1 = Tensor('b', 2, 1)

hydro_1d_invo_theo = Theorem(rf"""Let {L[u]} and {O[k]} be as in {Lu.ref} and {Ok.ref}. Then

 * An invariant non-degenerate metric is defined on the distribution {L[u]},
 * The distribution {L[u]} is invariant under any $(1,1)$-tensor {A1[i,j](u)} ({evo_tensor.ref}) and operator {b1[i,j,k](u)} for {j==const},
 * In the open domain {O[m]}, the distribution {L[u]} is involutive and defines an $m$-dimensional foliation {F[m]},
 * The metric on the leaves of {F[m]} is flat.

""", "See [Bogo2007a], theorem 1.")


# Let furthermore {Ok_def} denote the subset where {g(u)} has rank $k$.

# We define the {Lu.m} and the {Ok.m}. As e.g. per [Bogo2007a], if {g(u)} is smooth and degenerate, the {tspace.im} is the closure of the union {Union(
#     O[k], k, 0, n-1
# )}. If furthermore {g(u)} is analytic, then there is only one open domain {O[m]}, which is everywhere dense in {tspace} and its complement is a set of measure zero. In each non-empty domain {O[m]}, the subspaces {L[u]} form a smooth distribution of the constant dimension $m$. We can now state

gg = Definition(
    '(2,0)-tensor field',
    g
)
# b1, b2 = Symbol.symbols(r'\vmathbb{1} \vmathbb{2}')

hydro_smooth_counterexample = Notebook(
    'hydro_smooth_counterexample',
    'accompanying notebook'
)
partitions_prop = Proposition(
    rf"""Consider a {gg.im} with nonempty, open set {O[m]} as in {Ok.ref}. Then

* $g$ being smooth does not imply {Closure(Union(O[k], k, 0, n-1)) == tspace},
* if $g$ is analytic, then {Closure(O[m]) == tspace}.
""",
rf"""For the first point we will construct a counterexample that _is_ associated with a {hydrodynamic.long_ref} Poisson bracket. All functions used in this part will be smooth. Consider a diagonal metric {Eq(
    g(u),
    Matrix([
        [g[1](u), 0],
        [0, g[2](u)]
    ])
).bl} on the target manifold {tspace == Reals**2}. Together with {Eq(
    b(u),
    Frac(1,2)*grad[u]*Matrix([
        [g[1](u), b[1,2](u)],
        [-b[1,2](u), g[2](u)]
    ])
).ibl} this induces a hydrodynamic Poisson bracket if {Eq(
    g[2], b[1,2], 0
).ibl} or if {Eq(
    -g[2](u),g[1](u),b[1,2](u),g[0](u[1]+u[2])
).ibl} for all {uu}, see {hydro_smooth_counterexample}. We may stitch together the above families of Poisson brackets, as long as they are separated from each other, as for example as follows: {Relations(
    g[1](u) == g[0](u[1]+u[2]),
    -g[2](u) == Cases({
        u[1]+u[2] < -eps: g[1](u),
        u[1]+u[2] >= -eps: 0
    }),
    g[0](x) == Cases({
        Abs(x) > eps: blank != 0,
        Abs(x) <= eps: 0,
    })
).bl}, with {(eps > 0)} and {g[0]} constructed appropriately. We now have {Eq(
    Rank(g), Cases({
        u[1]+u[2] < -eps: 2,
        Abs(u[1]+u[2]) <= eps: 0,
        u[1]+u[2] > eps: 1
    })
).bl} and thus {Eq(
    Closure(Union(O[k], k, 0, n-1)),
    MySet(
        Contains((u[1], u[2]), tspace),
        Contains(u[1]+u[2], COInterval(-eps, sp.oo))
    ) != tspace
).bl}, which completes the proof of the first part.

For the second part we use the following factoid (see e.g. [Hogb2013], chapter 2.4, fact 25):

> A square matrix $A$ has rank $k$ if and only if $A$ has a nonsingular $k\times k$ submatrix, and every $(k+1)\times (k+1)$ submatrix of $A$ is singular.

As the determinant of a matrix with analytic coefficients is itself analytic,
square submatrices of $g$ that are singular on some open set {Subset(O[m],tspace)} stay singular on the whole of the {tspace.im}. For the same reason, square submatrices of $g$ that are nonsingular on some open set {Subset(O[m],tspace)} can not be singular on all of any open set. Given any {Contains(x, tspace)}, this includes _any_ open set {Subset(Prime(O),tspace)} containing $x$. Thus, every neighborhood of every point {Contains(x, tspace)} contains at least one point from {O[m]}, which is thus dense in {tspace.l}, i.e. its closure equals {tspace.l} (see e.g. [Bour1995], chapter 1, definition 10).""", rf"""""")

 #    g[1].d(u[2]), g[2].d(u[1]), b[1,2], 0
 # ).ibl} or if {Eq(
text += rf"""

For now, we do not require the {gg.im} to be associated with a Poisson bracket.
First, let us partition the {tspace.im} by defining the {Ok.m}. Next, to depart from the non-degenerate case, let us require that at least one {O[m]} is nonempty and open for some $m < n$. Now, in slight disagreement with [Bogo2007a], we have:

 {partitions_prop}

 {hydro_1d_invo_theo}


### in multiple spatial dimensions
## of Lie-Poisson type
### in one spatial dimension
[Bali1985]

### in multiple spatial dimensions

"""

# mapping some $d$-dimensional {xspace.im}
# smoothly onto another $n$-dimensional
# {uspace.im}.

#
# It is well known ([Dubr1983b], theorem 1) that if $d=1$ and $\det g \neq 0$,
#
# * {btog.expr.l} transform such that {christoffel.expr.l} are the
# Christoffel symbols of a differential-geometric {christoffel.label},
# * {Poisson(cdot, cdot).l} is skew-symmetric iff $g$ is symmetric and the
# {christoffel.im} is consistent with the metric $g$ and
# * {Poisson(cdot, cdot).l} satisfies the Jacobi identity iff the {christoffel.im}
# has no torsion and no curvature.
